site:
  title: EclipseStore Reference Manual
  url: https://docs.eclipsestore.io/
  robots: allow
content:
  sources:
  - url: https://github.com/eclipse-store/store.git
    branches: release/1x
    start_path: docs
  - url: https://github.com/eclipse-store/store.git
    branches: release/2x
    start_path: docs
  - url: https://github.com/eclipse-store/store.git
    branches: release/3x
    start_path: docs
  - url: https://github.com/eclipse-store/store.git
    branches: main
    start_path: docs
asciidoc:
  attributes:
    page-pagination: ''
    source-language: asciidoc@
    page-copyright-year: '2026'
ui: 
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
output:
  dir: ./site
antora:
  extensions:
  - require: '@antora/lunr-extension'


 
